version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ECU\Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  

volumes:
  mongodb_data:
