version: '3.8'
services:
    app:
        build:
          context: .\ECUBackend
          dockerfile: ECUBackend\Dockerfile
        ports:
          - "8080:80"
          - "1337:8080"
          - "1338:8081" 
        depends_on:
          - mongodb
          - mosquitto
        environment:
          - MONGO_CONNECTION_STRING=mongodb://mongodb:27017


    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
          - "27017:27017"
        volumes:
          - mongodb_data:/data/db

    mosquitto:
        image: eclipse-mosquitto
        hostname: mosquitto
        container_name: mosquitto
        restart: unless-stopped
        ports:
          - "1883:1883"
          - "9001:9001"
        volumes:
          - ./mosquitto:/etc/mosquitto
          - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
    mongodb_data:
    mosquitto_data:
    mosquitto_config:
    mosquitto_log:
